# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
# https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
name: unit-testing
on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    name: "Unit testing with ${{ matrix.DATASET }}"
    strategy:
      matrix:
        DATASET:
          - datasets/Dataset4.tsv
          - datasets/Dataset5.tsv
          - datasets/sars-cov-2-coronahit-rapid.tsv
          - datasets/sars-cov-2-coronahit-routine.tsv
          - datasets/sarscov2-SNF-A.tsv
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: apt-get
        run:  sudo apt-get install ca-certificates sra-toolkit
      - name: install bats-core
        run:  |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          cd -
          # test the command
          which bats
          bats -h
      - name: env
        run:  |
          pwd
          tree -d
      - name: unit testing - just env
        run:  |
          bats t/00_env.bats
      - name: unit testing with ${{ matrix.DATASET }}
        run:  |
          ls datasets || true
          export DATASET=$(realpath ${{ matrix.DATASET }})
          echo "Dataset is $DATASET"
          bats t/*
